### ISSUE TITLE
Doesn't work with Omeka 3.1.2

### ISSUE THREAD

**Issue by rosslcaputi** [utlib/BatchUpload#13]
I used Batch Upload successfully several times until I updated Omeka to version 3.1.2. The first time it failed, it said I hadn't set the PHP-CLI path. So I tried both:

`/usr/local/bin/php`
and
`/usr/local/bin/ea-php80`

The first option caused it to continue processing the job indeffinitely. The second kept returning me to the last step every time I started the processing the job. Oddly, after setting the PHP-CLI path, it never gave me an error message. Any suggestions?

**Comment by dicksonlaw583** [comment]
Please install [Job Diagnostics](https://github.com/utlib/JobDiagnostics) on your instance to test your job queue's setup. Once you have found a PHP-CLI setup that works with both short- and long-running jobs (see: [Diagnostics Tab](https://github.com/utlib/JobDiagnostics/wiki/Diagnostics-Tab)), start your import over from the beginning on a new job.

Since you have made changes to the PHP-CLI path, some processes may have been cut off and would never progress. You can inspect past jobs under [the Processes tab of Job Diagnostics](https://github.com/utlib/JobDiagnostics/wiki/Processes-Tab).

**Comment by rosslcaputi** [comment]
I've installed Job Diagnostics, but I still can't get it to work. For the PHP-CLI path, I've tried:
`/usr/local/bin/ea-php80`
`/usr/local/bin/php`
`usr/bin/php-cli`
`usr/bin/php`

The only info that Job Diagnostics is giving me is that the job keeps timing out. Any other suggestions?

**Comment by dicksonlaw583** [comment]
Since Job Diagnostics is showing a timeout, this means the problem is not related to Batch Upload specifically.

For the last 2 paths on your list, it should be `/usr/bin/php-cli` and `/usr/bin/php`. Leaving out the leading slash would make it a relative path, which won't likely exist in this case.

If you are running in a hosted environment, please consult your web hosting provider for the PHP-CLI path, as it could be none of the ones you listed.

If you have SSH/shell access to your environment, you can use `which php` to determine the path to your PHP executable, and use that for the PHP-CLI path.

**Comment by rosslcaputi** [comment]
I consulted with my web host and the first path I listed was correct. So if the issue isn't the PHP-CLI path, any other idea what it could be? By the way, I've tried posting to the Omeka forums to see if anyone else has had a similar issue with the update to version 3.1.2 and haven't gotten a response yet.

**Comment by dicksonlaw583** [comment]
I cannot tell for sure without error logs and process details for the interrupted jobs. However, since Job Diagnostics is also showing timeouts, I can tell that this is not an issue specific to Batch Upload.

**Comment by rosslcaputi** [comment]
I don't know why it hasn't been producing error messages, until this last attempt. It didn't show up in the error log, but it appeared on the plugin page: atchUpload_Application_DataContainer::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): "mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/archive9/archiveiraq.org/plugins/BatchUpload/libraries/BatchUpload/Application/DataContainer.php on line 24"

Any idea what this means?

**Comment by rosslcaputi** [comment]
I apologize, for a stupid mistake of my own I wasn't seeing the error logs. Now I'm seeing them in multiple places. In the error log file within the .htaccess folder, I'm getting this message:
`[12-Feb-2024 22:51:38 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/archive9/archiveiraq.org/themes/centerrow/items/show.php:9
Stack trace:
#0 /home/archive9/archiveiraq.org/application/libraries/Omeka/View.php(114): include()
#1 /home/archive9/archiveiraq.org/application/libraries/Zend/View/Abstract.php(889): Omeka_View->_run('/home/archive9/...')
#2 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#3 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/show.php', NULL)
#4 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#5 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#6 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#7 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#8 /home/archive9/archiveiraq.org/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /home/archive9/archiveiraq.org/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#10 /home/archive9/archiveiraq.org/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#11 /home/archive9/archiveiraq.org/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#12 /home/archive9/archiveiraq.org/index.php(23): Omeka_Application->run()
#13 {main}
  thrown in /home/archive9/archiveiraq.org/themes/centerrow/items/show.php on line 9`

There's another error log folder that's showing me: 
`[12-Feb-2024 19:10:22 UTC] PHP Warning:  Undefined array key "file_ingest_options" in /home/archive9/archiveiraq.org/application/models/Builder/Item.php on line 268
[12-Feb-2024 19:10:22 UTC] PHP Deprecated:  Creation of dynamic property Omeka_File_Ingest_Url::$_client is deprecated in /home/archive9/archiveiraq.org/application/libraries/Omeka/File/Ingest/Url.php on line 47
[12-Feb-2024 19:10:22 UTC] PHP Deprecated:  Creation of dynamic property Zend_Http_Client::$_stream_name is deprecated in /home/archive9/archiveiraq.org/application/libraries/Zend/Http/Client.php on line 982
[12-Feb-2024 19:10:24 UTC] PHP Deprecated:  Return type of BatchUpload_Application_DataContainer::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/archive9/archiveiraq.org/plugins/BatchUpload/libraries/BatchUpload/Application/DataContainer.php on line 24`

I believe line 268 in the item.php file is somewhere in here: 
`if (array_key_exists(self::FILES, $this->_fileMetadata)) {
            if (!array_key_exists(self::FILE_TRANSFER_TYPE, $this->_fileMetadata)) {
                throw new Omeka_Record_Builder_Exception(__("Must specify a file transfer type when attaching files to an item!"));
            }
            $this->addFiles(
                $this->_fileMetadata[self::FILE_TRANSFER_TYPE],
                $this->_fileMetadata[self::FILES],
                (array) $this->_fileMetadata[self::FILE_INGEST_OPTIONS]);`

I'm capable of a small amount of tinkering, but this is all over my head. Can you make sense of it?

**Comment by dicksonlaw583** [comment]
Of all the entries you showed, only this one is explicitly related to Batch Uploader:

```
[12-Feb-2024 19:10:24 UTC] PHP Deprecated:  Return type of BatchUpload_Application_DataContainer::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/archive9/archiveiraq.org/plugins/BatchUpload/libraries/BatchUpload/Application/DataContainer.php on line 24
```

You can fix this one by going to `/home/archive9/archiveiraq.org/plugins/BatchUpload/libraries/BatchUpload/Application/DataContainer.php` on your setup and replacing `public function jsonSerialize()` on line 24 with `public function jsonSerialize() : mixed`.

The remaining issues are related to other parts of your site (e.g. the Center Row theme, the item class of Omeka's core, etc.), so I am not able to support those.
