### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by lljohnston** [utlib/BatchUpload#3]
I'm running Omeka Classic 2.6.1 on Reclaim hosting.

My BatchLoad has a mapping set up, reads the csv just fine, the files are in the same directory as the csv and have no path, but it always fails on step 3. I tried it again to day with the same results as last fall (I also put this on that thread but started a new issue to bump it), and I was able to grab this from the error log:

[21-Feb-2019 17:26:26 UTC] PHP Fatal error: Uncaught Error: Class 'BatchUploadJob' not found in /home/gallery1/public_html/application/libraries/Omeka/Db/Table.php:682
Stack trace:
#0 /home/gallery1/public_html/application/libraries/Omeka/Db/Table.php(670): Omeka_Db_Table->recordFromData(Array)
#1 /home/gallery1/public_html/application/libraries/Omeka/Db/Table.php(214): Omeka_Db_Table->fetchObject(Object(Omeka_Db_Select), Array)
#2 /home/gallery1/public_html/application/libraries/globals.php(1878): Omeka_Db_Table->find(11)
#3 /home/gallery1/public_html/plugins/BatchUpload/libraries/BatchUpload/Job/GenerateRows.php(49): get_record_by_id('BatchUpload_Job', 11)
#4 /home/gallery1/public_html/application/libraries/Omeka/Job/Process/Wrapper.php(29): BatchUpload_Job_GenerateRows->perform()
#5 /home/gallery1/public_html/application/scripts/background.php(61): Omeka_Job_Process_Wrapper->run(Array)
#6 {main}
thrown in /home/gallery1/public_html/application/libraries/Omeka/Db/Table.php on line 682
[21-Feb-2019 17:38:09 UTC] PHP Warning: Declaration of BatchUpload_MappingSetsController::_redirectAfterAdd() should be compatible with Omeka_Controller_AbstractActionController::_redirectAfterAdd($record) in /home/gallery1/public_html/plugins/BatchUpload/controllers/MappingSetsController.php on line 8
[21-Feb-2019 17:38:09 UTC] PHP Warning: Declaration of BatchUpload_MappingSetsController::_redirectAfterEdit() should be compatible with Omeka_Controller_AbstractActionController::_redirectAfterEdit($record) in /home/gallery1/public_html/plugins/BatchUpload/controllers/MappingSetsController.php on line 8

**Comment by dicksonlaw583** [comment]
Fixed in 1.1.0.
